apiVersion: v1
kind: ConfigMap
metadata:
  name: dp-config
  namespace: kube-system
data:
  config.json: |
    {
      "resourceList": [{
        "resourceName": "nic", 
        "resourcePrefix": "amd.com", 
        "selectors": {
          "vendors": ["1dd8"], 
          "devices": ["1002"],
          "drivers": ["ionic"],
          "isRdma": true
        }
      },
      {
        "resourceName": "vnic",
        "resourcePrefix": "amd.com",
        "selectors": {
          "vendors": ["1dd8"], 
          "devices": ["1003"],
          "drivers": ["ionic"],
          "isRdma": true
        }
      }]
    }
