apiVersion: v1
kind: ConfigMap
metadata:
  # Name the ConfigMap uniquely per Helm release
  name: {{ .Release.Name }}-device-plugin-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: amd-nic
    app.kubernetes.io/part-of: amd-nic
    app.kubernetes.io/instance: {{ .Release.Name }}
  # Use the namespace where the Helm chart is deployed
data:
  # The config.json content for the AMD Network Device plugin
  config.json: |-
    {
      "resourceList": {{ toJson .Values.configMap.resourceList | nindent 6 }}
    }