apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-device-plugin
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "helm-charts-network-dp.labels" . | nindent 4 }}

