apiVersion: v2
name: network-device-plugin-charts
description: A Helm chart for AMD Network Device Plugin
home: https://github.com/ROCm/k8s-network-device-plugin
sources:
  - https://github.com/ROCm/k8s-network-device-plugin
icon: https://raw.githubusercontent.com/ROCm/k8s-device-plugin/master/helm/logo.png
keywords:
  - kubernetes
  - cluster
  - hardware
  - amd
  - nic
  - network
  - ai
  - deep learning

type: application
version: v1.1.0
appVersion: v1.1.0
kubeVersion: ">= 1.29.0-0"

maintainers:
- email: Sundaramurthy.Gurunathan@amd.com
  name: Sundara Gurunathan      
- email: Yuvarani.Shankar@amd.com
  name: Yuvarani Shankar
- email: Shrey.Ajmera@amd.com
  name: Shrey Ajmera
